version: '3.4'

networks:
  fun_chat_network:

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      - MYSQL_DATABASE=funchat
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
    volumes:
      - ./db/dump:/var/dump
    ports:
      - 3306:3306
    expose:
      - '3306'
    networks:
      - fun_chat_network
  fun-chat-api:
    build:
      context: .
      target: development
    volumes:
      - ./src:/fun-chat-api/src
    ports:
      - 4000:4000
    networks:
      - fun_chat_network
    env_file:
      - .env
    depends_on:
      - mysql


